#!/usr/bin/env python3
"""Prepare, supervise, and locally package one paired-test application run.

The launch configuration is generated by the paired application builder. Game
assets are checked in place. Only the ELF and immutable starting-save snapshot
are copied into a fresh, private run directory; the ISO and overlays remain at
their registered paths. The game receives no inherited experiment settings.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import platform
import re
import shutil
import signal
import stat
import subprocess
import sys
import threading
import uuid
from typing import Any

try:
    from . import native_modes, run_cases, run_package, texture_decode_policy
except ImportError:
    import native_modes  # type: ignore[no-redef]
    import run_cases  # type: ignore[no-redef]
    import run_package  # type: ignore[no-redef]
    import texture_decode_policy  # type: ignore[no-redef]


LAUNCH_SCHEMA = "yakumo-test-launch-v1"
PREFLIGHT_SCHEMA = "yakumo-test-preflight-v1"
RESULT_SCHEMA = "yakumo-test-launch-result-v1"
MAX_CONFIG_BYTES = 4 * 1024 * 1024
MAX_TREE_FILES = 10_000
MAX_TREE_BYTES = 32 * 1024 * 1024 * 1024
MAX_INPUT_BYTES = 16 * 1024 * 1024 * 1024
MAX_LOG_BYTES = 1024 * 1024
MAX_PREFLIGHT_BYTES = 64 * 1024
PREFLIGHT_TIMEOUT = 30.0
_HASH = re.compile(r"[0-9a-f]{64}\Z", re.ASCII)
_COMMIT = re.compile(r"[0-9a-fA-F]{7,40}\Z", re.ASCII)
_SAFE_ID = re.compile(r"[A-Za-z0-9_.-]{1,96}\Z", re.ASCII)
_REVISION = re.compile(r"source-sha256:[0-9a-f]{64}\Z", re.ASCII)
RENDERER_PROFILE_ENVIRONMENT = "MHP3RD_RENDERER_PROFILE_SHA256"
_ENV_PASSTHROUGH = frozenset({
    "HOME", "TMPDIR", "PATH", "LANG", "LC_ALL", "LC_CTYPE", "TERM",
    "DISPLAY", "WAYLAND_DISPLAY", "XAUTHORITY", "XDG_RUNTIME_DIR",
    "DBUS_SESSION_BUS_ADDRESS", "PULSE_SERVER", "PIPEWIRE_REMOTE",
    "SDL_AUDIODRIVER", "SDL_VIDEODRIVER",
})
_LAUNCH_FIELDS = frozenset({
    "schema", "role", "batch_id", "baseline_id", "baseline_commit",
    "source_commit", "binary", "inputs", "overlays", "starting_save",
    "cases", "work_root", "settings", "native_modes", "probe_selection",
    "configuration_sha256", "build_config_sha256", "recorder_revision",
    "baseline_provenance_sha256",
})
_PREFLIGHT_FIELDS = frozenset({
    "schema", "recorder_revision", "configuration_sha256",
    "build_config_sha256", "gameplay_source_commit", "baseline_sealed",
    "renderer_compiled", "aot_probes_compiled", "baseline_provenance_sha256",
})


class LaunchError(ValueError):
    """An untrusted launch input cannot be safely used."""


def _canonical(value: Any) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":"),
                      ensure_ascii=False, allow_nan=False).encode("utf-8")


def _sha256(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _same_or_beneath(path: Path, root: Path) -> bool:
    return path == root or root in path.parents


def _path(value: Any, label: str, *, kind: str | None = None) -> Path:
    if type(value) is not str or not value or any(ord(char) < 32 for char in value):
        raise LaunchError(f"{label} must be an absolute local path")
    path = Path(value)
    if not path.is_absolute() or ".." in path.parts or str(path) != os.path.normpath(value):
        raise LaunchError(f"{label} must be an absolute normalized path")
    if os.path.realpath(value) != value:
        raise LaunchError(f"{label} contains a symlink or path alias")
    current = Path(path.anchor)
    for part in path.parts[1:]:
        current /= part
        try:
            mode = current.lstat().st_mode
        except FileNotFoundError:
            if kind is not None:
                raise LaunchError(f"{label} does not exist") from None
            break
        if stat.S_ISLNK(mode):
            raise LaunchError(f"{label} contains a symlink")
    if kind is not None:
        try:
            mode = path.lstat().st_mode
        except FileNotFoundError:
            raise LaunchError(f"{label} does not exist") from None
        if not (stat.S_ISREG(mode) if kind == "file" else stat.S_ISDIR(mode)):
            raise LaunchError(f"{label} must be a regular {kind}")
    return path


def _regular_hash(path: Path, *, limit: int = MAX_INPUT_BYTES) -> tuple[int, str]:
    flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    flags |= getattr(os, "O_NONBLOCK", 0)
    try:
        fd = os.open(path, flags)
        try:
            before = os.fstat(fd)
            if not stat.S_ISREG(before.st_mode) or before.st_size > limit:
                raise LaunchError("input is not a bounded regular file")
            digest = hashlib.sha256()
            size = 0
            while True:
                chunk = os.read(fd, 1024 * 1024)
                if not chunk:
                    break
                size += len(chunk)
                if size > limit:
                    raise LaunchError("input exceeds file limit")
                digest.update(chunk)
            after = os.fstat(fd)
            if (before.st_dev, before.st_ino, before.st_size, before.st_mtime_ns) != (
                    after.st_dev, after.st_ino, after.st_size, after.st_mtime_ns) or size != before.st_size:
                raise LaunchError("input changed while it was hashed")
            return size, digest.hexdigest()
        finally:
            os.close(fd)
    except OSError as error:
        raise LaunchError(f"cannot hash input: {path}") from error


def _hash(value: Any, label: str) -> str:
    if type(value) is not str or not _HASH.fullmatch(value):
        raise LaunchError(f"{label} must be a lowercase SHA-256")
    return value


def _id(value: Any, label: str) -> str:
    if type(value) is not str or not _SAFE_ID.fullmatch(value) or value in (".", ".."):
        raise LaunchError(f"{label} must be an ASCII-safe ID")
    return value


def _commit(value: Any, label: str) -> str:
    if type(value) is not str or not _COMMIT.fullmatch(value):
        raise LaunchError(f"{label} must be a Git commit ID")
    return value.lower()


def _revision(value: Any) -> str:
    if type(value) is not str or not _REVISION.fullmatch(value):
        raise LaunchError("recorder_revision must be the compiled source digest")
    return value


def _relative(value: Any, label: str) -> Path:
    if type(value) is not str or not value or "\\" in value or "\x00" in value:
        raise LaunchError(f"{label} has an invalid relative path")
    posix = PurePosixPath(value)
    if posix.is_absolute() or any(part in ("", ".", "..") for part in value.split("/")) or str(posix) != value:
        raise LaunchError(f"{label} has an unsafe relative path")
    return Path(*posix.parts)


def _file_spec(value: Any, label: str) -> dict[str, Any]:
    if type(value) is not dict or set(value) != {"path", "sha256"}:
        raise LaunchError(f"{label} must have path and sha256")
    path = _path(value["path"], label + ".path", kind="file")
    digest = _hash(value["sha256"], label + ".sha256")
    if _regular_hash(path)[1] != digest:
        raise LaunchError(f"{label} hash differs")
    return {"path": path, "sha256": digest}


def _tree_spec(value: Any, label: str) -> dict[str, Any]:
    if type(value) is not dict or set(value) != {"path", "tree_id", "dirs", "files"}:
        raise LaunchError(f"{label} must have path, tree_id, dirs and files")
    root = _path(value["path"], label + ".path", kind="dir")
    tree_id = _hash(value["tree_id"], label + ".tree_id")
    if type(value["dirs"]) is not list or type(value["files"]) is not list:
        raise LaunchError(f"{label} must contain lists of directories and files")
    if len(value["files"]) > MAX_TREE_FILES or len(value["dirs"]) > MAX_TREE_FILES:
        raise LaunchError(f"{label} exceeds tree entry limit")
    dirs: list[str] = []
    for item in value["dirs"]:
        dirs.append(_relative(item, label + ".dirs").as_posix())
    files: list[dict[str, Any]] = []
    total = 0
    for item in value["files"]:
        if type(item) is not dict or set(item) != {"path", "size", "sha256"}:
            raise LaunchError(f"{label}.files has an invalid entry")
        rel = _relative(item["path"], label + ".files.path")
        size = item["size"]
        if type(size) is not int or not 0 <= size <= MAX_INPUT_BYTES:
            raise LaunchError(f"{label}.files.size is invalid")
        total += size
        if total > MAX_TREE_BYTES:
            raise LaunchError(f"{label} exceeds tree byte limit")
        files.append({"path": rel.as_posix(), "size": size,
                      "sha256": _hash(item["sha256"], label + ".files.sha256")})
    if dirs != sorted(set(dirs)) or [item["path"] for item in files] != sorted(set(item["path"] for item in files)):
        raise LaunchError(f"{label} tree entries must be sorted and unique")
    tree = {"dirs": dirs, "files": files}
    if _sha256(_canonical(tree)) != tree_id:
        raise LaunchError(f"{label} tree identity differs")
    _verify_tree(root, tree, label)
    return {"path": root, "tree_id": tree_id, "tree": tree}


def _verify_tree(root: Path, tree: dict[str, Any], label: str) -> None:
    actual_dirs: list[str] = []
    actual_files: list[dict[str, Any]] = []

    def visit(directory: Path) -> None:
        with os.scandir(directory) as entries:
            children = sorted(entries, key=lambda entry: entry.name)
        for child in children:
            rel = child.path[len(str(root)) + 1:]
            _relative(rel, label + ".entry")
            mode = child.stat(follow_symlinks=False).st_mode
            if stat.S_ISDIR(mode):
                actual_dirs.append(Path(rel).as_posix())
                visit(Path(child.path))
            elif stat.S_ISREG(mode):
                size, digest = _regular_hash(Path(child.path))
                actual_files.append({"path": Path(rel).as_posix(), "size": size, "sha256": digest})
            else:
                raise LaunchError(f"{label} contains a symlink or special file")
            if len(actual_dirs) + len(actual_files) > 2 * MAX_TREE_FILES:
                raise LaunchError(f"{label} exceeds tree entry limit")

    visit(root)
    if {"dirs": sorted(actual_dirs), "files": sorted(actual_files, key=lambda item: item["path"])} != tree:
        raise LaunchError(f"{label} tree differs from its manifest")


def _load_config(config_path: os.PathLike[str] | str) -> dict[str, Any]:
    source = _path(str(config_path), "launch config", kind="file")
    try:
        raw = run_package._read_file(source, MAX_CONFIG_BYTES)
        config = run_package._parse_json(raw)
    except (run_package.PackageError, ValueError, UnicodeError, RecursionError) as error:
        raise LaunchError("invalid launch configuration JSON") from error
    fields = set(config)
    optional = {"native_mode_schema", "renderer_profile_sha256"} | texture_decode_policy.FIELDS
    if not _LAUNCH_FIELDS <= fields or fields - _LAUNCH_FIELDS - optional or config.get("schema") != LAUNCH_SCHEMA:
        raise LaunchError("invalid launch configuration schema or fields")
    mode_schema = config.get("native_mode_schema")
    if "native_mode_schema" in config and mode_schema is None:
        raise LaunchError("unknown native mode schema")
    try:
        mode_fields = native_modes.fields(mode_schema)
    except ValueError as error:
        raise LaunchError("unknown native mode schema") from error
    try:
        texture_mode = texture_decode_policy.mode(config)
    except ValueError as error:
        raise LaunchError(str(error)) from error
    renderer_profile_sha256 = None
    if "renderer_profile_sha256" in config:
        renderer_profile_sha256 = _hash(config["renderer_profile_sha256"], "renderer_profile_sha256")
        if texture_decode_policy.FIELDS - fields:
            raise LaunchError("renderer profile requires complete texture decode policy fields")
    role = config["role"]
    if role not in ("baseline", "candidate"):
        raise LaunchError("role must be baseline or candidate")
    if role == "baseline" and texture_mode != "off":
        raise LaunchError("Baseline portable texture decoding must be off")
    if renderer_profile_sha256 is not None and role == "candidate" and texture_mode == "off":
        raise LaunchError("Candidate renderer profile requires verify or native texture decoding")
    batch_id = _id(config["batch_id"], "batch_id")
    baseline_id = _id(config["baseline_id"], "baseline_id")
    baseline_commit = _commit(config["baseline_commit"], "baseline_commit")
    source_commit = _commit(config["source_commit"], "source_commit")
    if role == "baseline" and not source_commit.startswith(baseline_commit):
        raise LaunchError("Baseline source commit differs from its registered reference")
    if type(config["binary"]) is not dict or type(config["inputs"]) is not dict or set(config["inputs"]) != {"iso", "elf"}:
        raise LaunchError("binary and inputs have invalid fields")
    binary = _file_spec(config["binary"], "binary")
    iso = _file_spec(config["inputs"]["iso"], "inputs.iso")
    elf = _file_spec(config["inputs"]["elf"], "inputs.elf")
    if elf["sha256"] != run_package.SUPPORTED_ELF_SHA256:
        raise LaunchError("ELF does not match the supported executable")
    overlays = _tree_spec(config["overlays"], "overlays")
    starting_save = _tree_spec(config["starting_save"], "starting_save")
    cases_raw = config["cases"]
    if type(cases_raw) is not dict or set(cases_raw) != {"path", "sha256"}:
        raise LaunchError("cases must have path and canonical sha256")
    cases_path = _path(cases_raw["path"], "cases.path", kind="file")
    cases = {"path": cases_path, "sha256": _hash(cases_raw["sha256"], "cases.sha256"),
             "file_sha256": _regular_hash(cases_path, limit=run_cases.MAX_CATALOG_BYTES)[1]}
    try:
        catalog = run_cases.load_case_catalog(cases_path)
    except run_cases.CaseCatalogError as error:
        raise LaunchError("invalid case catalog") from error
    catalog_sha256 = _sha256(_canonical(catalog))
    if catalog_sha256 != cases["sha256"]:
        raise LaunchError("case catalog canonical hash differs")
    work_root = _path(config["work_root"], "work_root")
    for source_path in (binary["path"], iso["path"], elf["path"], cases["path"]):
        if _same_or_beneath(source_path, work_root):
            raise LaunchError("work_root overlaps a read-only input")
    for source_path in (overlays["path"], starting_save["path"]):
        if _same_or_beneath(work_root, source_path) or _same_or_beneath(source_path, work_root):
            raise LaunchError("work_root overlaps an input tree")
    settings = config["settings"]
    if type(settings) is not dict or len(settings) > 256:
        raise LaunchError("settings must be a small string map")
    for key, value in settings.items():
        if (type(key) is not str or not key or len(key) > 128 or "=" in key or
                any(ord(char) < 32 or ord(char) == 127 for char in key) or key == "disc_image" or
                type(value) is not str or len(value) > 1024 or
                any(ord(char) < 32 or ord(char) == 127 for char in value)):
            raise LaunchError("settings contain an invalid key or value")
    modes = config["native_modes"]
    if type(modes) is not dict or set(modes) != set(mode_fields):
        raise LaunchError("native_modes must name exactly the helpers for the declared schema")
    for key, mode in modes.items():
        if mode not in ("off", "verify", "native"):
            raise LaunchError(f"invalid native mode for {key}")
        if role == "baseline" and mode != "off":
            raise LaunchError("Baseline native modes must all be off")
    if config["probe_selection"] != "all":
        raise LaunchError("paired runs require all certified probes")
    provenance = config["baseline_provenance_sha256"]
    if role == "baseline":
        provenance = _hash(provenance, "baseline_provenance_sha256")
    elif provenance != "":
        raise LaunchError("candidate baseline_provenance_sha256 must be empty")
    normalized = {
        "role": role, "batch_id": batch_id, "baseline_id": baseline_id,
        "baseline_commit": baseline_commit, "source_commit": source_commit,
        "binary": binary, "iso": iso, "elf": elf, "overlays": overlays,
        "starting_save": starting_save, "cases": cases,
        "catalog": catalog, "catalog_sha256": catalog_sha256,
        "work_root": work_root, "settings": settings, "native_modes": modes,
        "probe_selection": "all",
        "configuration_sha256": _hash(config["configuration_sha256"], "configuration_sha256"),
        "build_config_sha256": _hash(config["build_config_sha256"], "build_config_sha256"),
        "recorder_revision": _revision(config["recorder_revision"]),
        "baseline_provenance_sha256": provenance,
    }
    if mode_schema is not None:
        normalized["native_mode_schema"] = mode_schema
    if texture_decode_policy.SCHEMA_FIELD in config:
        normalized[texture_decode_policy.SCHEMA_FIELD] = texture_decode_policy.SCHEMA
        normalized[texture_decode_policy.MODE_FIELD] = texture_mode
    if renderer_profile_sha256 is not None:
        normalized["renderer_profile_sha256"] = renderer_profile_sha256
    return normalized


def _new_run_root(work_root: Path) -> tuple[str, Path, Path]:
    work_root.mkdir(parents=True, exist_ok=True, mode=0o700)
    _path(str(work_root), "work_root", kind="dir")
    runs = work_root / "runs"
    packages = work_root / "packages"
    for directory in (runs, packages):
        directory.mkdir(mode=0o700, exist_ok=True)
        _path(str(directory), "output directory", kind="dir")
    for _ in range(8):
        run_id = "run-" + uuid.uuid4().hex
        run_root = runs / run_id
        try:
            run_root.mkdir(mode=0o700)
            return run_id, run_root, packages / run_id
        except FileExistsError:
            continue
    raise LaunchError("cannot reserve a new run identity")


def _write_new(path: Path, value: bytes) -> None:
    with path.open("xb") as stream:
        stream.write(value)


def _write_json(path: Path, value: dict[str, Any]) -> None:
    _write_new(path, json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False,
                                allow_nan=False).encode("utf-8") + b"\n")


def _copy_checked(source: Path, target: Path, size: int, digest: str, *, mode: int) -> None:
    with source.open("rb") as incoming, target.open("xb") as outgoing:
        shutil.copyfileobj(incoming, outgoing, length=1024 * 1024)
    target.chmod(mode)
    if _regular_hash(target) != (size, digest):
        raise LaunchError("copied input differs from its verified source")


def _prepare_data(config: dict[str, Any], run_root: Path) -> Path:
    data = run_root / "data"
    data.mkdir(mode=0o700)
    source_elf = config["elf"]["path"]
    elf_size, elf_hash = _regular_hash(source_elf)
    if elf_hash != config["elf"]["sha256"]:
        raise LaunchError("ELF changed after configuration validation")
    _copy_checked(source_elf, data / "EBOOT.ELF", elf_size, elf_hash, mode=0o444)
    save = config["starting_save"]
    target_save = data / "ms0" / "PSP" / "SAVEDATA" / "ULJM05800"
    target_save.mkdir(parents=True, mode=0o700)
    for dirname in save["tree"]["dirs"]:
        (target_save / _relative(dirname, "save directory")).mkdir(parents=True, exist_ok=True, mode=0o700)
    for entry in save["tree"]["files"]:
        rel = _relative(entry["path"], "save file")
        target = target_save / rel
        target.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
        _copy_checked(save["path"] / rel, target, entry["size"], entry["sha256"], mode=0o600)
    _verify_tree(target_save, save["tree"], "copied starting_save")
    lines = [f"{key}={value}\n" for key, value in sorted(config["settings"].items())]
    lines.append(f"disc_image={config['iso']['path']}\n")
    _write_new(data / "settings.ini", "".join(lines).encode("utf-8"))
    return data


def _environment(config: dict[str, Any], data: Path, run_id: str,
                 record_dir: Path | None = None, context_sha256: str | None = None,
                 basis_sha256: str | None = None, cases_path: Path | None = None) -> dict[str, str]:
    env = {key: value for key, value in os.environ.items() if key in _ENV_PASSTHROUGH}
    env["MHP3RD_DATA_DIR"] = str(data)
    env["MHP3RD_OVERLAY_DIR"] = str(config["overlays"]["path"])
    env["MHP3RD_RECORD_PROBES"] = config["probe_selection"]
    env.update(config["native_modes"])
    env[texture_decode_policy.ENVIRONMENT] = config.get(texture_decode_policy.MODE_FIELD, "off")
    if "renderer_profile_sha256" in config:
        env[RENDERER_PROFILE_ENVIRONMENT] = config["renderer_profile_sha256"]
    env["MHP3RD_WINDOW_TITLE"] = f"Yakumo {config['role'].title()} {config['batch_id']} {run_id[:12]}"
    if record_dir is not None:
        assert context_sha256 is not None and basis_sha256 is not None and cases_path is not None
        env.update({
            "MHP3RD_RECORD_DIR": str(record_dir),
            "MHP3RD_RECORD_ROLE": config["role"],
            "MHP3RD_RECORD_RUN_ID": run_id,
            "MHP3RD_RECORD_BATCH_ID": config["batch_id"],
            "MHP3RD_RECORD_BASELINE_ID": config["baseline_id"],
            "MHP3RD_RECORD_BASELINE_COMMIT": config["baseline_commit"],
            "MHP3RD_RECORD_CONTEXT_SHA256": context_sha256,
            "MHP3RD_RECORD_CASE_CATALOG": str(cases_path),
            "MHP3RD_RECORD_CASE_CATALOG_SHA256": config["catalog_sha256"],
            "MHP3RD_RECORD_PREREQUISITES_SHA256": basis_sha256,
        })
    return env


def _capture(stream: Any, path: Path, limit: int) -> None:
    retained = 0
    truncated = False
    with path.open("xb") as output:
        while chunk := stream.read(64 * 1024):
            take = min(len(chunk), max(0, limit - retained))
            if take:
                output.write(chunk[:take])
                retained += take
            if take != len(chunk):
                truncated = True
        if truncated:
            output.write(b"\n[output truncated by test supervisor]\n")
    stream.close()


def _execute(command: list[str], env: dict[str, str], output_dir: Path,
             label: str, *, timeout: float | None, limit: int) -> tuple[int | None, bool, Path, Path]:
    stdout = output_dir / f"{label}.stdout.log"
    stderr = output_dir / f"{label}.stderr.log"
    process = subprocess.Popen(command, env=env, cwd=output_dir, stdout=subprocess.PIPE,
                               stderr=subprocess.PIPE, start_new_session=True)
    assert process.stdout is not None and process.stderr is not None
    threads = [
        threading.Thread(target=_capture, args=(process.stdout, stdout, limit), daemon=True),
        threading.Thread(target=_capture, args=(process.stderr, stderr, limit), daemon=True),
    ]
    for thread in threads:
        thread.start()
    timed_out = False
    try:
        process.wait(timeout=timeout)
    except subprocess.TimeoutExpired:
        timed_out = True
        try:
            os.killpg(process.pid, signal.SIGTERM)
        except ProcessLookupError:
            pass
        try:
            process.wait(timeout=5)
        except subprocess.TimeoutExpired:
            try:
                os.killpg(process.pid, signal.SIGKILL)
            except ProcessLookupError:
                pass
            process.wait()
    except KeyboardInterrupt:
        try:
            os.killpg(process.pid, signal.SIGTERM)
        except ProcessLookupError:
            pass
        process.wait()
        raise
    finally:
        for thread in threads:
            thread.join(timeout=10)
    return process.returncode, timed_out, stdout, stderr


def _read_preflight(path: Path, returncode: int | None, timed_out: bool,
                    config: dict[str, Any]) -> dict[str, Any]:
    if timed_out or returncode != 0:
        raise LaunchError("binary preflight did not complete successfully")
    try:
        raw = run_package._read_file(path, MAX_PREFLIGHT_BYTES)
        value = run_package._parse_json(raw, flat=True)
    except (run_package.PackageError, ValueError, UnicodeError, RecursionError) as error:
        raise LaunchError("binary preflight did not emit one bounded JSON object") from error
    mode_schema = config.get("native_mode_schema")
    expected_fields = set(_PREFLIGHT_FIELDS) | ({"native_mode_schema"} if mode_schema is not None else set())
    texture_schema = config.get(texture_decode_policy.SCHEMA_FIELD)
    if texture_schema is not None:
        expected_fields |= texture_decode_policy.FIELDS
    renderer_profile_sha256 = config.get("renderer_profile_sha256")
    if renderer_profile_sha256 is not None:
        expected_fields.add("renderer_profile_sha256")
    if set(value) != expected_fields or value["schema"] != PREFLIGHT_SCHEMA:
        raise LaunchError("binary preflight schema or fields differ")
    if mode_schema is not None and value["native_mode_schema"] != mode_schema:
        raise LaunchError("binary preflight native mode schema differs from the launch manifest")
    if texture_schema is not None and (
            value[texture_decode_policy.SCHEMA_FIELD] != texture_schema or
            value[texture_decode_policy.MODE_FIELD] != config[texture_decode_policy.MODE_FIELD]):
        raise LaunchError("binary preflight texture decode policy differs from the launch manifest")
    if renderer_profile_sha256 is not None and value["renderer_profile_sha256"] != renderer_profile_sha256:
        raise LaunchError("binary preflight renderer profile digest differs from the launch manifest")
    expected = {
        "recorder_revision": config["recorder_revision"],
        "configuration_sha256": config["configuration_sha256"],
        "build_config_sha256": config["build_config_sha256"],
        "gameplay_source_commit": config["source_commit"],
        "baseline_sealed": config["role"] == "baseline",
        "renderer_compiled": True,
        "aot_probes_compiled": True,
        "baseline_provenance_sha256": config["baseline_provenance_sha256"],
    }
    for key, item in expected.items():
        if value[key] != item:
            raise LaunchError(f"binary preflight {key} differs from the launch manifest")
    return value


def _context(config: dict[str, Any], run_id: str) -> dict[str, Any]:
    return {
        "schema": run_package.CONTEXT_SCHEMA,
        "run_id": run_id,
        "game_sha256": config["iso"]["sha256"],
        "elf_sha256": config["elf"]["sha256"],
        "overlay_sha256": config["overlays"]["tree_id"],
        "starting_save_sha256": config["starting_save"]["tree_id"],
        "config_sha256": config["configuration_sha256"],
        "build_config_sha256": config["build_config_sha256"],
        "case_catalog_sha256": config["catalog_sha256"],
        "source_commit": config["source_commit"],
        "platform_os": platform.system(),
        "platform_arch": platform.machine(),
    }


def _inputs_unchanged(config: dict[str, Any]) -> bool:
    try:
        for key in ("binary", "iso", "elf"):
            if _regular_hash(config[key]["path"])[1] != config[key]["sha256"]:
                return False
        if _regular_hash(config["cases"]["path"], limit=run_cases.MAX_CATALOG_BYTES)[1] != config["cases"]["file_sha256"]:
            return False
        for key in ("overlays", "starting_save"):
            _verify_tree(config[key]["path"], config[key]["tree"], key)
    except (LaunchError, OSError):
        return False
    return True


def _stop_reason(journal_path: Path, returncode: int | None, timed_out: bool) -> tuple[str, str, int | None]:
    if timed_out:
        return "unknown", "timeout", None
    if returncode is None:
        return "unknown", "launch_failed", None
    if returncode < 0:
        number = -returncode
        try:
            name = signal.Signals(number).name
        except ValueError:
            name = str(number)
        return "signaled", "signal:" + name, None
    if not journal_path.is_file():
        return "exited", "missing_journal", returncode
    journal = run_package.read_journal(journal_path)
    if journal["issue"] != "none":
        return "exited", "journal_" + journal["issue"], returncode
    records = journal["records"]
    end = records[-1]["fields"] if records and records[-1]["kind"] == 2 else {}
    reason = end.get("stop_reason")
    return "exited", reason if type(reason) is str and reason else "missing_run_end", returncode


def _publish_result(result: dict[str, Any], result_path: os.PathLike[str] | str | None) -> None:
    if result_path is None:
        return
    target = _path(str(result_path), "result_path")
    if target.exists() or target.is_symlink():
        raise LaunchError("result_path already exists")
    _path(str(target.parent), "result_path parent", kind="dir")
    temporary = target.parent / ("." + target.name + "." + uuid.uuid4().hex + ".tmp")
    try:
        _write_json(temporary, result)
        os.link(temporary, target, follow_symlinks=False)
    finally:
        temporary.unlink(missing_ok=True)


def run_launch(config_path: os.PathLike[str] | str, *, timeout: float | None = None,
               result_path: os.PathLike[str] | str | None = None,
               prepare_only: bool = False) -> dict[str, Any]:
    """Run a prepared role once. ``timeout`` is for bounded synthetic tests."""
    if timeout is not None and (type(timeout) not in (int, float) or not 0 < timeout <= 3600):
        raise LaunchError("timeout must be a positive test-only duration")
    config = _load_config(config_path)
    if result_path is not None:
        target = _path(str(result_path), "result_path")
        if target.exists() or target.is_symlink():
            raise LaunchError("result_path already exists")
        _path(str(target.parent), "result_path parent", kind="dir")
        for source in (config["overlays"]["path"], config["starting_save"]["path"]):
            if _same_or_beneath(target, source):
                raise LaunchError("result_path overlaps a read-only input tree")
    run_id, run_root, package_path = _new_run_root(config["work_root"])
    context = _context(config, run_id)
    context_path = run_root / "context.json"
    supervisor_path = run_root / "supervisor.json"
    recording_dir = run_root / "recording"
    result: dict[str, Any] = {
        "schema": RESULT_SCHEMA, "role": config["role"], "run_id": run_id,
        "status": "preparing", "run_directory": str(run_root),
        "recording_directory": str(recording_dir), "context_path": str(context_path),
        "supervisor_path": None, "package_path": None,
        "recording_complete": False, "evidence_complete": False,
        "exit_code": None, "process_status": "unknown", "stop_reason": "not_started",
        "source_inputs_unchanged": None, "validation_issues": [],
    }
    try:
        data = _prepare_data(config, run_root)
        cases_path = run_root / "cases.json"
        _write_new(cases_path, _canonical(config["catalog"]))
        _write_json(context_path, context)
        preflight_env = _environment(config, data, run_id)
        code, timed_out, preflight_stdout, _ = _execute(
            [str(config["binary"]["path"]), "--test-preflight"], preflight_env,
            run_root, "preflight", timeout=PREFLIGHT_TIMEOUT, limit=MAX_PREFLIGHT_BYTES)
        result["preflight"] = _read_preflight(preflight_stdout, code, timed_out, config)
        result["source_inputs_unchanged"] = _inputs_unchanged(config)
        if not result["source_inputs_unchanged"]:
            raise LaunchError("source inputs changed during preparation")
        if prepare_only:
            result["status"] = "prepared"
            result["stop_reason"] = "prepare_only"
            return result
        context_sha256 = _sha256(_canonical(context))
        basis_sha256 = run_package.prerequisite_basis_sha256(
            context, config["baseline_id"], config["baseline_commit"])
        game_env = _environment(config, data, run_id, recording_dir,
                                context_sha256, basis_sha256, cases_path)
        if _regular_hash(config["binary"]["path"])[1] != config["binary"]["sha256"]:
            raise LaunchError("binary changed after preflight")
        try:
            code, timed_out, _, _ = _execute([str(config["binary"]["path"])], game_env,
                                               run_root, "game", timeout=timeout,
                                               limit=MAX_LOG_BYTES)
        except OSError as error:
            code, timed_out = None, False
            result["launch_error"] = str(error)[:1024]
        process_status, stop_reason, exit_code = _stop_reason(recording_dir / "events.journal", code, timed_out)
        result.update({"process_status": process_status, "stop_reason": stop_reason,
                       "exit_code": exit_code})
        supervisor = {"schema": run_package.SUPERVISOR_SCHEMA, "run_id": run_id,
                      "status": process_status, "exit_code": exit_code,
                      "stop_reason": stop_reason}
        _write_json(supervisor_path, supervisor)
        result["supervisor_path"] = str(supervisor_path)
        result["source_inputs_unchanged"] = _inputs_unchanged(config)
        journal_path = recording_dir / "events.journal"
        if journal_path.is_file() and result["source_inputs_unchanged"]:
            package = run_package.package_run(recording_dir, context_path, package_path, supervisor_path)
            result["package_path"] = str(package_path)
            validation = package["validation"]
            result["recording_complete"] = validation["recording_complete"]
            result["validation_issues"] = validation["issues"]
            result["evidence_complete"] = (
                validation["recording_complete"] and validation["metadata_complete"] and
                validation["identity_binding"] == "bound")
        else:
            result["validation_issues"] = ["source_inputs_changed" if not result["source_inputs_unchanged"]
                                           else "missing_journal"]
        result["status"] = "completed" if result["evidence_complete"] else "incomplete"
        return result
    except (LaunchError, run_package.PackageError, run_cases.CaseCatalogError, OSError) as error:
        result["status"] = "preflight_failed" if result["process_status"] == "unknown" and result["stop_reason"] == "not_started" else "incomplete"
        result["error"] = str(error)[:1024]
        return result
    finally:
        # Keep the final outcome with the evidence even when the native
        # launcher's private handoff file is removed after its dialog closes.
        _publish_result(result, run_root / "result.json")
        if result_path is not None:
            _publish_result(result, result_path)


def result_directory(result_path: os.PathLike[str] | str) -> Path:
    """Return the verified local run directory named by a prior result file."""
    source = _path(str(result_path), "result_path", kind="file")
    try:
        value = run_package._parse_json(run_package._read_file(source, run_package.MAX_METADATA_BYTES))
    except (run_package.PackageError, ValueError, UnicodeError, RecursionError) as error:
        raise LaunchError("invalid result JSON") from error
    if value.get("schema") != RESULT_SCHEMA or type(value.get("run_id")) is not str:
        raise LaunchError("invalid result schema")
    run_id = _id(value["run_id"], "result.run_id")
    directory = _path(value.get("run_directory"), "result.run_directory", kind="dir")
    if directory.name != run_id or directory.parent.name != "runs":
        raise LaunchError("result run directory does not match its identity")
    if value.get("recording_directory") != str(directory / "recording") or \
            value.get("context_path") != str(directory / "context.json"):
        raise LaunchError("result paths do not match its run directory")
    return directory


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--config", type=Path)
    source.add_argument("--result-directory", type=Path,
                        help="print the local run directory in a prior result file")
    parser.add_argument("--result-file", type=Path)
    parser.add_argument("--prepare-only", action="store_true")
    args = parser.parse_args(argv)
    try:
        if args.result_directory is not None:
            if args.result_file is not None or args.prepare_only:
                parser.error("--result-directory cannot launch or prepare a run")
            print(result_directory(args.result_directory), flush=True)
            return 0
        result = run_launch(args.config, result_path=args.result_file,
                            prepare_only=args.prepare_only)
    except (LaunchError, OSError) as error:
        print(json.dumps({"schema": RESULT_SCHEMA, "status": "invalid_launch",
                          "error": str(error)[:1024]}), flush=True)
        return 2
    print(json.dumps(result, sort_keys=True, ensure_ascii=False), flush=True)
    return 0 if result["status"] in ("completed", "prepared") else 1


if __name__ == "__main__":
    raise SystemExit(main())
