#include "resources/source_authority.hpp"
#include <cstdint>
#include <functional>
#include <iostream>
#include <stdexcept>
#include <string>
#include <vector>

namespace {
using namespace mhp3rd::resources;
constexpr std::uint32_t kOwner=0x09000000u,kOtherOwner=0x09100000u;
constexpr std::uint32_t kCommand=0x09400000u,kDescriptor=0x08230000u;
constexpr std::uint32_t kSlot=kOwner+SourceAuthority::kSlotOffset;
unsigned checks{},failures{},cases{};
void expect(bool condition,const std::string &message){++checks;if(!condition)throw std::runtime_error(message);}
AuthorityToken tracked(const AuthorityIssue &issue){
    if(!issue.event.recorded || issue.token.serial==0u)throw std::runtime_error("Observation was not tracked");return issue.token;
}
void accepted(AuthorityEvent event){if(!event.ok())throw std::runtime_error("Valid receipt rejected: "+std::to_string(static_cast<int>(event.error)));}
SourceAuthorityConfig config(){
    SourceAuthorityConfig c;c.ram_bytes=64u*1024u*1024u;c.owner_allocator=0x08100000u;c.command_allocator=0x08100100u;
    c.supported_code={0xF6300296C8D954E5ull,1u,0x0A0E7460u,0x088B0400u,0x088B7DE0u,0x088652C4u,0x08865378u};return c;
}
struct Fragment{AuthorityToken token;SourceFragment spec;};
struct Fixture{
    SourceAuthorityConfig cfg;SourceAuthority authority;AuthorityToken owner{},command{};std::uint32_t descriptor_number{};
    explicit Fixture(SourceAuthorityConfig c=config()):cfg(c),authority(cfg){
        owner=tracked(authority.construct_owner(kOwner,SourceAuthority::kOwnerBytes,c.owner_allocator,SourceAuthority::kLobbyVtable,c.supported_code));
        command=tracked(authority.allocate_command(kCommand,144u,c.command_allocator));
    }
    AuthorityToken load(std::uint32_t total=32u,AuthorityToken who={}){
        if(who.serial==0u)who=owner;return tracked(authority.begin_load({who,17u,5u,total,SourceRoute::DataBinState8,cfg.supported_code}));
    }
    Fragment fragment(AuthorityToken l,std::uint32_t offset=0u,std::uint32_t count=32u,std::uint32_t total=32u,
                      bool first=true,bool last=true,bool transform=true,bool hash=false,std::uint32_t destination=kSlot){
        const auto descriptor=tracked(authority.begin_descriptor(kDescriptor+32u*descriptor_number++,32u));
        SourceFragment s{l,descriptor,destination,17u,5u,offset,count,total,first,last,transform,hash,SourceCopyMode::Inline,cfg.supported_code};
        return {tracked(authority.begin_fragment(s)),s};
    }
    void fresh(const Fragment &f){accepted(authority.observe_descriptor(f.token,f.spec));}
    void read(const Fragment &f){fresh(f);accepted(authority.observe_read(f.token,f.spec.bytes));}
    void copy(const Fragment &f){fresh(f);accepted(authority.observe_copy(f.token,f.spec.destination+f.spec.offset,f.spec.bytes,f.spec.copy_mode));}
    void transform(const Fragment &f){fresh(f);accepted(authority.observe_transform(f.token,f.spec.destination+f.spec.offset,
        f.spec.deobfuscate?(f.spec.bytes+3u)&~3u:0u,f.spec.hash_flag));}
    void finish(const Fragment &f){read(f);copy(f);if(f.spec.deobfuscate||f.spec.hash_flag)transform(f);
        fresh(f);accepted(authority.observe_postprocess(f.token));fresh(f);accepted(authority.observe_terminal(f.token,true));}
    void publish(std::uint32_t n=32u,bool transform=true,bool hash=false){auto l=load(n);finish(fragment(l,0u,n,n,true,true,transform,hash));}
    SourcePermitResult permit(AuthorityToken who={},std::uint32_t source_n=32u,AuthorityToken cmd={}){
        if(who.serial==0u)who=owner;if(cmd.serial==0u)cmd=command;
        return authority.permit(who,cmd,0u,source_n,0u,36u,cfg.supported_code);
    }
};
void test(const char *name,const std::function<void()> &body){++cases;try{body();std::cout<<"ok   "<<name<<'\n';}
    catch(const std::exception &e){++failures;std::cerr<<"FAIL "<<name<<": "<<e.what()<<'\n';}}
}
int main(){
 test("complete receipt publishes exact bounds and current permit",[]{Fixture f;expect(!f.permit().ok(),"Empty owner was ready");f.publish();auto p=f.permit();
    expect(p.ok(),"Complete source unavailable");expect(p.permit.source_base==kSlot&&p.permit.source_bytes==32u,"Source bounds fabricated");
    expect(p.permit.command_base==kCommand&&p.permit.command_bytes==144u,"Command request bounds changed");
    expect(p.permit.digest==SourceDigestEvidence::NotChecked,"Digest pass invented");expect(f.authority.revalidate(p.permit,f.cfg.supported_code)==AuthorityError::None,"Fresh permit stale");});
 test("copied mode and computed-only digest remain distinct",[]{for(bool hash:{false,true}){Fixture f;f.publish(32u,hash,hash);auto p=f.permit();expect(p.ok(),"Mode flow failed");
    expect(p.permit.digest==(hash?SourceDigestEvidence::ComputedOnly:SourceDigestEvidence::NotChecked),"Wrong integrity evidence");
    auto forged=p.permit;forged.digest=SourceDigestEvidence::ReferenceCompared;expect(f.authority.revalidate(forged,f.cfg.supported_code)!=AuthorityError::None,"Forged integrity pass accepted");}});
 test("short zero and error reads require a fresh exact receipt",[]{Fixture f;auto r=f.fragment(f.load());for(std::int64_t count:{3,0,-1}){f.fresh(r);auto e=f.authority.observe_read(r.token,count);expect(!e.ok(),"Incomplete read treated as full");expect(!f.permit().ok(),"Partial read published");}f.finish(r);expect(f.permit().ok(),"Exact retry cannot recover");});
 test("retry cannot reuse an old descriptor snapshot",[]{Fixture f;auto r=f.fragment(f.load());f.fresh(r);(void)f.authority.observe_read(r.token,3);expect(!f.authority.observe_read(r.token,32).ok(),"Retry reused stale descriptor evidence");expect(!f.permit().ok(),"Unresampled retry published");});
 test("retirement without copy and acknowledgement cannot publish",[]{Fixture f;auto r=f.fragment(f.load());f.read(r);(void)f.authority.observe_terminal(r.token,true);expect(!f.permit().ok(),"Bare retirement published");});
 test("missing transform or postprocess is rejected",[]{for(bool omit_transform:{false,true}){Fixture f;auto r=f.fragment(f.load());f.read(r);f.copy(r);if(!omit_transform)f.transform(r);else (void)f.authority.observe_postprocess(r.token);(void)f.authority.observe_terminal(r.token,true);expect(!f.permit().ok(),"Missing phase published");}});
 test("failure terminal remains unavailable",[]{Fixture f;auto r=f.fragment(f.load());f.read(r);f.copy(r);f.transform(r);f.fresh(r);accepted(f.authority.observe_postprocess(r.token));(void)f.authority.observe_terminal(r.token,false);expect(!f.permit().ok(),"Failed terminal published");});
 test("multi-fragment source publishes only at exact final end",[]{Fixture f;auto l=f.load();auto first=f.fragment(l,0u,16u,32u,true,false);f.finish(first);expect(!f.permit().ok(),"Prefix published");auto last=f.fragment(l,16u,16u,32u,false,true);f.finish(last);expect(f.permit().ok(),"Exact fragments failed");});
 test("queued fragments can be submitted before ordered processing",[]{Fixture f;auto l=f.load();auto first=f.fragment(l,0u,16u,32u,true,false);auto last=f.fragment(l,16u,16u,32u,false,true);f.finish(first);expect(!f.permit().ok(),"Queued suffix counted as transferred");f.finish(last);expect(f.permit().ok(),"Queued ordered fragments did not publish");});
 test("out-of-order queued read poisons its candidate",[]{Fixture f;auto l=f.load();auto first=f.fragment(l,0u,16u,32u,true,false);auto last=f.fragment(l,16u,16u,32u,false,true);(void)first;(void)f.authority.observe_descriptor(last.token,last.spec);auto e=f.authority.observe_read(last.token,16u);expect(!e.ok(),"Future fragment read accepted before predecessor completion");expect(!f.permit().ok(),"Out-of-order candidate ready");});
 test("a load cannot change transform or digest flags midstream",[]{Fixture f;auto l=f.load();f.finish(f.fragment(l,0u,16u,32u,true,false));auto later=f.fragment(l,16u,16u,32u,false,true,false,false);(void)f.authority.observe_descriptor(later.token,later.spec);(void)f.authority.observe_read(later.token,16u);expect(!f.permit().ok(),"Flag-changing load ready");});
 test("gap overlap and premature final flag stay ineligible",[]{for(unsigned mode=0;mode<3u;++mode){Fixture f;auto l=f.load();if(mode<2u){f.finish(f.fragment(l,0u,16u,32u,true,false));auto r=f.fragment(l,mode==0u?20u:12u,12u,32u,false,true);(void)f.authority.observe_read(r.token,r.spec.bytes);}else{auto r=f.fragment(l,0u,16u,32u,true,true);(void)f.authority.observe_terminal(r.token,true);}expect(!f.permit().ok(),"Invalid fragment sequence published");}});
 test("changed descriptor metadata poisons a pending candidate",[]{Fixture f;auto r=f.fragment(f.load());auto changed=r.spec;changed.resource_id=18u;expect(!f.authority.observe_descriptor(r.token,changed).ok(),"Changed resource ID accepted");(void)f.authority.observe_read(r.token,32);expect(!f.permit().ok(),"Changed metadata published");});
 test("descriptor address aliases share reuse generation",[]{Fixture f;auto r=f.fragment(f.load());f.read(r);auto reused=f.authority.begin_descriptor(kDescriptor|0x40000000u,32u);expect(reused.event.recorded,"Descriptor alias reuse untracked");(void)f.authority.observe_copy(r.token,kSlot,32u,SourceCopyMode::Inline);(void)f.authority.observe_transform(r.token,kSlot,32u,false);(void)f.authority.observe_postprocess(r.token);(void)f.authority.observe_terminal(r.token,true);expect(!f.permit().ok(),"Recycled descriptor completed old receipt");});
 test("partially overlapping descriptors retire old generations",[]{Fixture f;auto r=f.fragment(f.load());f.read(r);f.copy(r);f.transform(r);f.fresh(r);accepted(f.authority.observe_postprocess(r.token));(void)f.authority.begin_descriptor(kDescriptor+4u,32u);(void)f.authority.observe_descriptor(r.token,r.spec);(void)f.authority.observe_terminal(r.token,true);expect(!f.permit().ok(),"Overlapping descriptor reuse retained source");});
 test("unsupported copy enum cannot manufacture a completed route",[]{Fixture f;auto l=f.load();auto descriptor=tracked(f.authority.begin_descriptor(kDescriptor,32u));SourceFragment spec{l,descriptor,kSlot,17u,5u,0u,32u,32u,true,true,true,false,static_cast<SourceCopyMode>(99),f.cfg.supported_code};auto token=tracked(f.authority.begin_fragment(spec));(void)f.authority.observe_descriptor(token,spec);(void)f.authority.observe_read(token,32);(void)f.authority.observe_copy(token,kSlot,32u,spec.copy_mode);(void)f.authority.observe_transform(token,kSlot,32u,false);(void)f.authority.observe_postprocess(token);(void)f.authority.observe_descriptor(token,spec);(void)f.authority.observe_terminal(token,true);expect(!f.permit().ok(),"Unknown copy mode authorized source");});
 test("foreign descriptor writes poison pending metadata",[]{Fixture f;auto r=f.fragment(f.load());f.read(r);(void)f.authority.observe_unknown_write(kDescriptor+8u,4u);(void)f.authority.observe_copy(r.token,kSlot,32u,SourceCopyMode::Inline);(void)f.authority.observe_transform(r.token,kSlot,32u,false);(void)f.authority.observe_postprocess(r.token);(void)f.authority.observe_terminal(r.token,true);expect(!f.permit().ok(),"Descriptor metadata overwrite ignored");});
 test("five transferred bytes do not become eight source bytes",[]{Fixture f;f.publish(5u);auto p=f.permit({},5u);expect(p.ok()&&p.permit.source_bytes==5u,"Rounded footprint expanded source");expect(!f.permit({},8u).ok(),"Untransferred padding authorized");});
 test("rounded write cannot cross slot capacity",[]{Fixture f;auto l=f.load(SourceAuthority::kSlotBytes);f.finish(f.fragment(l,0u,SourceAuthority::kSlotBytes-1u,SourceAuthority::kSlotBytes,true,false));auto r=f.fragment(l,SourceAuthority::kSlotBytes-1u,1u,SourceAuthority::kSlotBytes,false,true);(void)f.authority.observe_read(r.token,1);(void)f.authority.observe_copy(r.token,r.spec.destination+r.spec.offset,1u,SourceCopyMode::Inline);(void)f.authority.observe_transform(r.token,r.spec.destination+r.spec.offset,4u,false);(void)f.authority.observe_postprocess(r.token);(void)f.authority.observe_terminal(r.token,true);expect(!f.permit().ok(),"Out-of-slot transform authorized");});
 test("source and command subranges cannot use allocation slack",[]{Fixture f;f.publish();expect(!f.authority.permit(f.owner,f.command,0u,33u,0u,36u,f.cfg.supported_code).ok(),"Source slack authorized");expect(!f.authority.permit(f.owner,f.command,0u,32u,120u,36u,f.cfg.supported_code).ok(),"Command slack authorized");expect(!f.authority.permit(f.owner,f.command,0xFFFFFFF0u,32u,0u,36u,f.cfg.supported_code).ok(),"Wrapped source range authorized");});
 test("owner allocator vtable extent and RAM mapping are checked",[]{for(unsigned mode=0;mode<5u;++mode){auto c=config();SourceAuthority a(c);auto code=c.supported_code;const auto result=a.construct_owner(mode==0u?0x04000000u:mode==1u?0xFFFFFFF0u:kOwner,mode==2u?SourceAuthority::kOwnerBytes-1u:SourceAuthority::kOwnerBytes,mode==3u?c.command_allocator:c.owner_allocator,mode==4u?0x0896FA78u:SourceAuthority::kLobbyVtable,code);expect(!result.event.ok(),"Invalid owner admitted");}});
 test("resource and group identity widths are bounded",[]{for(bool group:{false,true}){Fixture f;f.publish();auto load=f.authority.begin_load({f.owner,group?17u:65536u,group?256u:5u,32u,SourceRoute::DataBinState8,f.cfg.supported_code});expect(!load.event.ok()&&!f.permit().ok(),"Impossible descriptor identity retained publication");}});
 test("owner and command may be separate leases in one allocator",[]{auto c=config();c.command_allocator=c.owner_allocator;Fixture f(c);f.publish();expect(f.permit().ok(),"Same allocator unnecessarily rejected distinct leases");});
 test("live allocation aliases cannot overlap",[]{Fixture f;auto result=f.authority.allocate_command((kOwner+64u)|0x40000000u,144u,f.cfg.command_allocator);expect(!result.event.ok(),"Command alias overlaps owner");});
 test("reset invalidates cached permits and old receipts",[]{Fixture f;f.publish();auto p=f.permit();expect(p.ok(),"No initial permit");accepted(f.authority.reset_owner(f.owner));expect(f.authority.revalidate(p.permit,f.cfg.supported_code)!=AuthorityError::None&&!f.permit().ok(),"Reset left authority current");f.publish();expect(f.permit().ok(),"Fresh post-reset source unavailable");});
 test("command release rejects an otherwise ready source permit",[]{Fixture f;f.publish();auto p=f.permit();accepted(f.authority.release_command(f.command));expect(!f.permit().ok()&&f.authority.revalidate(p.permit,f.cfg.supported_code)!=AuthorityError::None,"Freed command used");});
 test("foreign writes invalidate published sources through aliases",[]{Fixture f;f.publish();auto p=f.permit();(void)f.authority.observe_unknown_write((kSlot+4u)|0x40000000u,4u);expect(!f.permit().ok()&&f.authority.revalidate(p.permit,f.cfg.supported_code)!=AuthorityError::None,"Alias write retained publication");});
 test("foreign owner-vptr write revokes construction authority",[]{Fixture f;f.publish();auto p=f.permit();(void)f.authority.observe_unknown_write(kOwner|0x40000000u,4u);expect(!f.permit().ok()&&f.authority.revalidate(p.permit,f.cfg.supported_code)!=AuthorityError::None,"Vptr write retained owner binding");auto new_load=f.authority.begin_load({f.owner,17u,5u,32u,SourceRoute::DataBinState8,f.cfg.supported_code});expect(!new_load.event.ok(),"New load revived unproven owner binding");});
 test("foreign writes between copy and transform poison candidates",[]{Fixture f;auto r=f.fragment(f.load());f.read(r);f.copy(r);(void)f.authority.observe_unknown_write(kSlot+8u,4u);(void)f.authority.observe_transform(r.token,kSlot,32u,false);(void)f.authority.observe_postprocess(r.token);(void)f.authority.observe_terminal(r.token,true);expect(!f.permit().ok(),"Pending candidate ignored foreign write");});
 test("pending external writer blocks publication until a new transfer",[]{Fixture f;auto writer=tracked(f.authority.begin_external_write(kSlot,32u));auto r=f.fragment(f.load());f.read(r);f.copy(r);f.transform(r);f.fresh(r);accepted(f.authority.observe_postprocess(r.token));f.fresh(r);accepted(f.authority.observe_terminal(r.token,true));expect(!f.permit().ok(),"Pending external writer ignored");(void)f.authority.observe_external_write(writer,kSlot+4u,4u);(void)f.authority.prove_external_quiescent(writer);expect(!f.permit().ok(),"Quiescence resurrected poisoned bytes");f.publish();expect(f.permit().ok(),"Fresh transfer after quiescence failed");});
 test("old writer survives cancel free and exact address reuse",[]{Fixture f;auto old=f.fragment(f.load());f.read(old);(void)f.authority.cancel_request(old.token);accepted(f.authority.release_owner(f.owner));f.owner=tracked(f.authority.construct_owner(kOwner,SourceAuthority::kOwnerBytes,f.cfg.owner_allocator,SourceAuthority::kLobbyVtable,f.cfg.supported_code));auto next=f.fragment(f.load());f.read(next);f.copy(next);f.transform(next);f.fresh(next);accepted(f.authority.observe_postprocess(next.token));f.fresh(next);accepted(f.authority.observe_terminal(next.token,true));expect(!f.permit().ok(),"Old writer hazard vanished on free");(void)f.authority.observe_copy(old.token,kSlot,32u,SourceCopyMode::Inline);(void)f.authority.prove_request_quiescent(old.token);expect(!f.permit().ok(),"Old terminal resurrected newer publication");f.publish();expect(f.permit().ok(),"New clean generation failed");});
 test("stale completion with changed actual destination poisons other owner",[]{Fixture f;auto other=tracked(f.authority.construct_owner(kOtherOwner,SourceAuthority::kOwnerBytes,f.cfg.owner_allocator,SourceAuthority::kLobbyVtable,f.cfg.supported_code));auto l=f.load(32u,other);auto second=f.fragment(l,0u,32u,32u,true,true,true,false,kOtherOwner+SourceAuthority::kSlotOffset);f.finish(second);expect(f.permit(other).ok(),"Second owner unavailable");auto stale=f.fragment(f.load());f.read(stale);(void)f.authority.cancel_request(stale.token);(void)f.authority.observe_copy(stale.token,kOtherOwner+SourceAuthority::kSlotOffset,32u,SourceCopyMode::Inline);expect(!f.permit(other).ok(),"Changed stale destination missed second owner");});
 test("unrelated writes do not erase independent ready source",[]{Fixture f;f.publish();(void)f.authority.observe_unknown_write(0x09600000u,32u);expect(f.permit().ok(),"Unrelated write erased source");});
 test("pending command output writer blocks permits",[]{Fixture f;f.publish();auto writer=tracked(f.authority.begin_external_write(kCommand,36u));expect(!f.permit().ok(),"Pending command writer ignored");accepted(f.authority.prove_external_quiescent(writer));expect(f.permit().ok(),"Unwritten command capacity did not recover after quiescence");});
 test("invalid huge configuration is bounded before storage allocation",[]{auto c=config();c.max_requests=static_cast<std::size_t>(-1);SourceAuthority a(c);expect(a.failure()==AuthorityError::InvalidConfig,"Huge configuration did not fail boundedly");});
 test("code epoch change invalidates all prior permits",[]{Fixture f;f.publish();auto p=f.permit();auto next=f.cfg.supported_code;++next.epoch;(void)f.authority.code_changed(next);expect(f.authority.revalidate(p.permit,f.cfg.supported_code)!=AuthorityError::None&&!f.permit().ok(),"Old code epoch retained authority");});
 test("unsupported load start cannot lose an untracked writer",[]{Fixture f;f.publish();(void)f.authority.begin_load({f.owner,17u,5u,32u,SourceRoute::Unsupported,f.cfg.supported_code});expect(f.authority.failure()==AuthorityError::ObservationLost&&!f.permit().ok(),"Unsupported reload left authority reusable without writer tracking");});
 test("regressive code epoch cannot revive old owner evidence",[]{Fixture f;f.publish();auto next=f.cfg.supported_code;++next.epoch;(void)f.authority.code_changed(next);(void)f.authority.code_changed(f.cfg.supported_code);expect(f.authority.failure()==AuthorityError::ObservationLost&&!f.permit().ok(),"Old code epoch became eligible again");});
 test("permit fields and replacement instances cannot be forged",[]{Fixture f;f.publish();auto p=f.permit();auto forged=p.permit;++forged.source_bytes;expect(f.authority.revalidate(forged,f.cfg.supported_code)!=AuthorityError::None,"Source bound tamper accepted");forged=p.permit;++forged.command.serial;expect(f.authority.revalidate(forged,f.cfg.supported_code)!=AuthorityError::None,"Command identity tamper accepted");Fixture other;other.publish();expect(other.authority.revalidate(p.permit,other.cfg.supported_code)!=AuthorityError::None,"Old instance permit accepted");});
 test("observation loss latches fail closed",[]{Fixture f;f.publish();auto p=f.permit();(void)f.authority.observer_lost();expect(f.authority.failure()!=AuthorityError::None&&!f.permit().ok(),"Loss retained authority");expect(f.authority.revalidate(p.permit,f.cfg.supported_code)!=AuthorityError::None,"Permit survived lost observations");});
 test("request and writer budgets fail closed without forgetting hazards",[]{auto c=config();c.max_requests=1u;c.max_external_writers=1u;Fixture f(c);auto first=f.fragment(f.load());(void)f.authority.begin_fragment(first.spec);expect(!f.permit().ok(),"Capacity event authorized source");Fixture w(c);auto a=tracked(w.authority.begin_external_write(kSlot,4u));(void)a;auto b=w.authority.begin_external_write(kSlot+4u,4u);expect(!b.event.ok()&&w.authority.failure()!=AuthorityError::None,"Writer overflow silently dropped hazard");});
 test("partial descriptor size is not a certified record",[]{Fixture f;auto d=f.authority.begin_descriptor(kDescriptor,1u);expect(!d.event.ok(),"One-byte descriptor footprint accepted");});
 test("failed retirement retains a writer until explicit quiescence",[]{Fixture f;auto old=f.fragment(f.load());f.read(old);(void)f.authority.observe_terminal(old.token,false);f.publish();expect(!f.permit().ok(),"Failed retirement dropped pending writer");(void)f.authority.prove_request_quiescent(old.token);expect(f.permit().ok(),"Unwritten stale request did not clear after proven quiescence");});
 test("missing terminal snapshot cannot drop writer hazard",[]{Fixture f;auto old=f.fragment(f.load());f.read(old);f.copy(old);f.transform(old);f.fresh(old);accepted(f.authority.observe_postprocess(old.token));(void)f.authority.observe_terminal(old.token,true);f.publish();expect(!f.permit().ok(),"Incomplete terminal receipt dropped writer");(void)f.authority.prove_request_quiescent(old.token);expect(f.permit().ok(),"Fresh source blocked after genuine quiescence");});
 test("unknown ongoing writer callback fails closed globally",[]{Fixture f;f.publish();(void)f.authority.observe_external_write({99999u,99999u},0x09600000u,4u);expect(f.authority.failure()==AuthorityError::ObservationLost&&!f.permit().ok(),"Untracked active writer forgotten");});
 test("unknown owner reload cannot preserve an unrelated publication",[]{Fixture f;auto old=f.owner;accepted(f.authority.release_owner(old));f.owner=tracked(f.authority.construct_owner(kOwner,SourceAuthority::kOwnerBytes,f.cfg.owner_allocator,SourceAuthority::kLobbyVtable,f.cfg.supported_code));f.publish();(void)f.authority.begin_load({old,17u,5u,32u,SourceRoute::DataBinState8,f.cfg.supported_code});expect(f.authority.failure()==AuthorityError::ObservationLost&&!f.permit().ok(),"Unaccounted reload retained source");});
 test("rejected overlapping allocation cannot preserve source authority",[]{for(bool command:{false,true}){Fixture f;f.publish();if(command)(void)f.authority.allocate_command(kSlot,36u,0x081F0000u);else(void)f.authority.construct_owner(kOwner,SourceAuthority::kOwnerBytes,0x081F0000u,SourceAuthority::kLobbyVtable,f.cfg.supported_code);expect(f.authority.failure()==AuthorityError::ObservationLost&&!f.permit().ok(),"Unknown overlapping allocation retained old ownership");}});
 test("cached and uncached owner tokens retain physical source bounds",[]{Fixture f;accepted(f.authority.release_owner(f.owner));f.owner=tracked(f.authority.construct_owner(kOwner|0x40000000u,SourceAuthority::kOwnerBytes,f.cfg.owner_allocator,SourceAuthority::kLobbyVtable,f.cfg.supported_code));f.publish();auto p=f.permit();expect(p.ok()&&p.permit.source_base==(kSlot|0x40000000u),"Valid owner alias was not admitted");});
 test("descriptor history is bounded and aliases consume one slot",[]{auto c=config();c.max_descriptors=1u;Fixture f(c);auto a=f.authority.begin_descriptor(kDescriptor,32u);expect(a.event.recorded,"First descriptor rejected");auto alias=f.authority.begin_descriptor(kDescriptor|0x40000000u,32u);expect(alias.event.recorded,"Alias used a second history slot");auto b=f.authority.begin_descriptor(kDescriptor+32u,32u);expect(!b.event.ok()&&f.authority.failure()!=AuthorityError::None,"Descriptor history overflow ignored");});
 test("monotonic serial budget cannot wrap into valid old tokens",[]{auto c=config();c.serial_ceiling=8u;SourceAuthority a(c);for(unsigned i=0;i<32u&&a.failure()==AuthorityError::None;++i)(void)a.begin_descriptor(kDescriptor,32u);expect(a.failure()==AuthorityError::CounterExhausted,"Serial exhaustion not latched");});
 std::cout<<cases<<" cases, "<<checks<<" checks, "<<failures<<" failures\n";return failures?1:0;
}
